project_id = "cfihcvudcwujylipqngk"

[functions.create-partner]
verify_jwt = false

[functions.request-call]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.reciter-call]
verify_jwt = true

[functions.moyasar-webhook]
verify_jwt = false

[functions.verify-certificate]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false
