project_id = "cfihcvudcwujylipqngk"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.create-partner]
    verify_jwt = false
  [functions.create-payment]
    verify_jwt = false
  [functions.moyasar-webhook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.reciter-call]
    verify_jwt = true
  [functions.exam-call]
    verify_jwt = true
  [functions.request-call]
    verify_jwt = false
  [functions.signup-student]
    verify_jwt = false
  [functions.signup-reciter]
    verify_jwt = false
  [functions.list-reciter-accounts]
    verify_jwt = true
  [functions.activate-reciter]
    verify_jwt = true
  [functions.list-student-accounts]
    verify_jwt = true
  [functions.create-student]
    verify_jwt = true
  [functions.update-student]
    verify_jwt = true
  [functions.verify-certificate]
    verify_jwt = false
  [functions.verify-payment]
    verify_jwt = false
  [functions.whatsapp-webhook]
    verify_jwt = false
